name: UndeadWave
version: 1.0.0
main: com.akira.undeadwave.UndeadWave
authors: [Yukino_Akira]
api-version: 1.20
depend: [AkiraCore]

permissions:
  undeadwave.user:
    default: true
  undeadwave.admin:
    default: op

commands:
  undeadwave:
    permission: undeadwave.user
    aliases: [uw]
  undeadwaveadmin:
    permission: undeadwave.admin
    aliases: [uwadmin, uwa]