package com.akira.undeadwave.core.weapon;

public enum WeaponType {
    WOOD_KNIFE, IRON_KNIFE, DIAMOND_KNIFE,
    BLOODY_BLADE, VAMPIRIC_BLADE,
    LUCKY_SWORD, FATE_SWORD,
    LONG_SWORD, WIND_SWORD, WHIRLWIND_SWORD,
    SHOCK_BLADE, STORM_BLADE,
    PIERCING_KNIFE, TRUE_KNIFE, TRUTH_SWORD,

    PISTOL, GOLD_PISTOL,
    SHOTGUN, DIAMOND_SHOTGUN,
    FIRE_LAUNCHER, LAVA_LAUNCHER,
    GAMBLER_GUN, FATE_GUN,
    COPPER_MINER, GOLD_MINER, NETHERITE_MINER,
    ROCKET_LAUNCHER, ANCIENT_ROCKET_LAUNCHER,
    SNIPER, INFERNAL_SNIPER
}
