package com.akira.undeadwave.core.weapon;

public enum WeaponType {
    WOOD_KNIFE, IRON_KNIFE, DIAMOND_KNIFE,
    BLOODY_BLADE, VAMPIRIC_BLADE,
    GAMBLER_SWORD, LUCKY_SWORD, FATE_SWORD,
    LONG_SWORD, WIND_SWORD, WHRILWIND_SWORD,
    SHOCK_BLADE, STORM_BLADE,
    PIERCING_KNIFE, TRUE_KNIFE, SWORD_OF_TRUTH;

}
